name: cos-registration-agent
base: core22
version: '0.1'
summary: COS registration agent is identifying the robot to the COS server
description: |
  COS registration agent is responsible for identifying 
  the robot to the COS server as well as uploading robot 
  specific data to the server (dashboard, UID, etc).

grade: devel
confinement: strict

slots:
  configuration:
    interface: content
    source:
      read:
        - $SNAP

plugs:
  rob-cos-common-write:
    interface: content
    target: $SNAP_COMMON

parts:
  cos-registration-agent:
    plugin: python
    source: .

apps:
  cos-registration-agent:
    command: bin/cos-registration-agent
    plugs: [network, rob-cos-common-write]
