name: cos-registration-agent
base: core22
version: '0.1'
summary: COS registration agent is identifying the robot to the COS server
description: |
  COS registration agent is responsible for identifying 
  the robot to the COS server as well as uploading robot 
  specific data to the server (dashboard, UID, etc).

grade: devel
confinement: strict

slots:
  configuration:
    interface: content
    source:
      read:
        - $SNAP

plugs:
  rob-cos-common-write:
    interface: content
    target: $SNAP_COMMON/rob-cos-shared-data
  configuration-read:
    interface: content
    target: $SNAP_COMMON/configuration

hooks:
  connect-plug-configuration-read:
    plugs: [network]
  disconnect-plug-configuration-read:
    plugs: [network]

parts:
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
  cos-registration-agent:
    plugin: python
    source: .

apps:
  update-device-configuration:
    command: usr/bin/update-device-configuration.sh
    daemon: oneshot
    install-mode: disable
    plugs: [network, rob-cos-common-write, configuration-read]
  cos-registration-agent:
    command: bin/cos-registration-agent
    plugs: [network, rob-cos-common-write, configuration-read]
