#!/bin/sh -e

CONFIGURATION_FILE_PATH=$SNAP_COMMON/configuration/device.yaml
CONFIG_PATH="$(snapctl get configuration-path)"

if [ ! -f "$CONFIGURATION_FILE_PATH" ]; then
    echo "Configuration file '$CONFIGURATION_FILE_PATH' does not exist."
    # Use fallback configuration mechanism if the configuration-path is set
    if [ -n "${CONFIG_PATH}" ]; then
        echo "Configuration-path parameter has been set"
        CONFIGURATION_FILE_PATH=/root/${CONFIG_PATH}/device.yaml
    else
        echo "No valid configuration file has been found"
        exit 1
    fi
fi

URL=$(grep '^url:' "$CONFIGURATION_FILE_PATH" | cut -d ' ' -f 2)
UID=$(grep '^uid:' "$CONFIGURATION_FILE_PATH" | cut -d ' ' -f 2)
$SNAP/bin/cos-registration-agent delete --url $URL --uid $UID
